import { Vendor, Product, Order, Promotion, VendorStats } from '@/types/market';

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Apex Tech Haven',
    slug: 'apex-tech',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 1420,
    joinedDate: 'Jan 2023',
    verified: true,
    location: 'Austin, TX',
    description: 'Premier curator of audio gear, flagship workspace devices, and premium accessories.',
    responseRate: '99% (within 1 hr)',
    shippingSpeed: 'Same day dispatch',
    badge: 'Top Rated Vendor',
  },
  {
    id: 'vendor-2',
    name: 'Urban Aura Studio',
    slug: 'urban-aura',
    logo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 890,
    joinedDate: 'Aug 2023',
    verified: true,
    location: 'Brooklyn, NY',
    description: 'Sustainable everyday carry, contemporary streetwear, and weather-proof commuter bags.',
    responseRate: '96% (within 2 hrs)',
    shippingSpeed: '1-2 business days',
    badge: 'Featured Brand',
  },
  {
    id: 'vendor-3',
    name: 'GreenLeaf Artisans',
    slug: 'greenleaf-artisans',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 610,
    joinedDate: 'Nov 2023',
    verified: true,
    location: 'Portland, OR',
    description: 'Organic wellness essentials, solid oak desk organizers, and hand-poured botanical candles.',
    responseRate: '98% (within 3 hrs)',
    shippingSpeed: '1-3 business days',
    badge: 'Eco-Certified',
  },
  {
    id: 'vendor-4',
    name: 'Titan Pro Ergonomics',
    slug: 'titan-pro',
    logo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 520,
    joinedDate: 'Feb 2024',
    verified: true,
    location: 'Seattle, WA',
    description: 'Aerospace-grade aluminum laptop stands, mechanical keyboards, and precision desk mats.',
    responseRate: '94% (within 4 hrs)',
    shippingSpeed: 'Same day dispatch',
    badge: 'Ergo Verified',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Apex Tech Haven',
      rating: 4.9,
      reviewCount: 1420,
      verified: true,
      location: 'Austin, TX',
    },
    title: 'AuraSphere ANC Spatial Wireless Headphones',
    slug: 'aurasphere-anc-spatial-headphones',
    description: 'Studio-grade acoustic architecture with active hybrid noise cancellation, 45-hour continuous battery life, and lossless Bluetooth 5.4 transmission.',
    price: 289,
    compareAtPrice: 349,
    currency: 'USD',
    sku: 'APX-AU-01',
    category: 'Electronics',
    subCategory: 'Audio',
    tags: ['wireless', 'noise-cancelling', 'audiophile', 'bluetooth'],
    stock: 24,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 312,
    featured: true,
    status: 'active',
    specifications: {
      'Battery Life': '45 Hours (ANC On)',
      'Connectivity': 'Bluetooth 5.4 / USB-C Lossless',
      'Driver Size': '40mm Custom Beryllium Diaphragm',
      'Weight': '255g',
      'Warranty': '2 Years Comprehensive',
    },
    shipping: {
      freeShipping: true,
      estimatedDays: '1-2 Days',
      cost: 0,
    },
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'prod-102',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Apex Tech Haven',
      rating: 4.9,
      reviewCount: 1420,
      verified: true,
      location: 'Austin, TX',
    },
    title: 'ProVision 4K 144Hz HDR Creator Monitor',
    slug: 'provision-4k-144hz-creator-monitor',
    description: 'Ultra-accurate IPS Black panel calibrated with 99% DCI-P3 color gamut, 90W USB-C power delivery hub, and anti-glare nano texture.',
    price: 649,
    compareAtPrice: 799,
    currency: 'USD',
    sku: 'APX-PV-4K',
    category: 'Electronics',
    subCategory: 'Displays',
    tags: ['monitor', '4k', 'creator', 'usb-c'],
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    reviewCount: 154,
    featured: true,
    status: 'active',
    specifications: {
      'Resolution': '3840 x 2160 (4K UHD)',
      'Refresh Rate': '144Hz Variable',
      'Color Gamut': '99% DCI-P3, Delta E < 1',
      'Power Delivery': '90W USB-C Hub',
      'Warranty': '3 Years Zero Bright Dot',
    },
    shipping: {
      freeShipping: true,
      estimatedDays: '2-3 Days',
      cost: 0,
    },
    createdAt: '2026-02-10T12:00:00Z',
  },
  {
    id: 'prod-103',
    vendorId: 'vendor-2',
    vendor: {
      id: 'vendor-2',
      name: 'Urban Aura Studio',
      rating: 4.8,
      reviewCount: 890,
      verified: true,
      location: 'Brooklyn, NY',
    },
    title: 'Nomad Roll-Top Weatherproof Commuter Backpack',
    slug: 'nomad-rolltop-weatherproof-backpack',
    description: 'Constructed from waterproof 100% recycled Cordura fabric with magnetic Fidlock closures, TSA-approved laptop sleeve, and ergonomic airflow back cushioning.',
    price: 165,
    compareAtPrice: 195,
    currency: 'USD',
    sku: 'UA-BK-09',
    category: 'Fashion & Bags',
    subCategory: 'Bags',
    tags: ['backpack', 'weatherproof', 'commuter', 'sustainable'],
    stock: 42,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    reviewCount: 188,
    featured: true,
    status: 'active',
    specifications: {
      'Capacity': '26 Liters expandable to 32L',
      'Material': 'Recycled 500D Cordura Ripstop',
      'Laptop Compartment': 'Fits up to 16" MacBook Pro',
      'Hardware': 'Fidlock V-Buckles & YKK Aquaguard',
      'Warranty': 'Lifetime Guarantee',
    },
    shipping: {
      freeShipping: true,
      estimatedDays: '2-4 Days',
      cost: 0,
    },
    createdAt: '2026-01-20T08:30:00Z',
  },
  {
    id: 'prod-104',
    vendorId: 'vendor-2',
    vendor: {
      id: 'vendor-2',
      name: 'Urban Aura Studio',
      rating: 4.8,
      reviewCount: 890,
      verified: true,
      location: 'Brooklyn, NY',
    },
    title: 'Merino Wool Minimalist Technical Overshirt',
    slug: 'merino-wool-minimalist-overshirt',
    description: 'Thermo-regulating 100% Australian Merino wool woven with water-resistant nanocoating. Designed for all-season versatility and crisp modern style.',
    price: 135,
    compareAtPrice: 160,
    currency: 'USD',
    sku: 'UA-SH-22',
    category: 'Fashion & Bags',
    subCategory: 'Clothing',
    tags: ['merino', 'apparel', 'minimalist', 'sustainable'],
    stock: 19,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.7,
    reviewCount: 94,
    featured: false,
    status: 'active',
    specifications: {
      'Fabric': '100% 210 GSM Merino Wool',
      'Care': 'Machine Wash Gentle / Air Dry',
      'Fit': 'Contemporary Relaxed Fit',
      'Origin': 'Ethically Tailored in Portugal',
      'Warranty': '1 Year Craftsmanship',
    },
    shipping: {
      freeShipping: false,
      estimatedDays: '3-5 Days',
      cost: 9.99,
    },
    createdAt: '2026-02-01T15:00:00Z',
  },
  {
    id: 'prod-105',
    vendorId: 'vendor-3',
    vendor: {
      id: 'vendor-3',
      name: 'GreenLeaf Artisans',
      rating: 4.9,
      reviewCount: 610,
      verified: true,
      location: 'Portland, OR',
    },
    title: 'Solid American Walnut Modular Desk Shelf',
    slug: 'solid-walnut-modular-desk-shelf',
    description: 'Handcrafted from FSC-certified sustainably harvested walnut timber. Elevates dual monitors to ergonomic eye level while storing your keyboard and accessories underneath.',
    price: 189,
    compareAtPrice: 220,
    currency: 'USD',
    sku: 'GL-DS-01',
    category: 'Home & Workspace',
    subCategory: 'Furniture',
    tags: ['woodwork', 'workspace', 'ergonomic', 'walnut'],
    stock: 14,
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 220,
    featured: true,
    status: 'active',
    specifications: {
      'Dimensions': '46" W x 9" D x 4.2" H',
      'Weight Capacity': '65 lbs (Dual Ultrawide Support)',
      'Material': 'Solid American Black Walnut & Anodized Steel Legs',
      'Finish': 'Natural Organic Hardwax Oil',
      'Warranty': '5 Years Structural',
    },
    shipping: {
      freeShipping: true,
      estimatedDays: '2-4 Days',
      cost: 0,
    },
    createdAt: '2026-01-05T09:00:00Z',
  },
  {
    id: 'prod-106',
    vendorId: 'vendor-3',
    vendor: {
      id: 'vendor-3',
      name: 'GreenLeaf Artisans',
      rating: 4.9,
      reviewCount: 610,
      verified: true,
      location: 'Portland, OR',
    },
    title: 'Botanical Ultrasonic Ceramic Aromatherapy Diffuser',
    slug: 'botanical-ceramic-aroma-diffuser',
    description: 'Minimalist matte ceramic dome creates soothing cool mist with ultra-quiet 24dB operation, ambient warm glow, and automatic waterless shutoff.',
    price: 78,
    compareAtPrice: 95,
    currency: 'USD',
    sku: 'GL-DF-88',
    category: 'Home & Workspace',
    subCategory: 'Wellness',
    tags: ['wellness', 'ceramic', 'diffuser', 'organic'],
    stock: 35,
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    reviewCount: 145,
    featured: false,
    status: 'active',
    specifications: {
      'Reservoir': '300ml (Up to 12 Hours Runtime)',
      'Material': 'Handcrafted Ceramic & BPA-free interior',
      'Coverage': 'Up to 500 sq ft',
      'Timer Modes': '1h / 3h / 6h / Continuous',
      'Warranty': '2 Years Replacement',
    },
    shipping: {
      freeShipping: false,
      estimatedDays: '3-5 Days',
      cost: 6.50,
    },
    createdAt: '2026-02-14T11:20:00Z',
  },
  {
    id: 'prod-107',
    vendorId: 'vendor-4',
    vendor: {
      id: 'vendor-4',
      name: 'Titan Pro Ergonomics',
      rating: 4.7,
      reviewCount: 520,
      verified: true,
      location: 'Seattle, WA',
    },
    title: 'ApexType CNC Aluminum Wireless Mechanical Keyboard (75%)',
    slug: 'apextype-cnc-mechanical-keyboard',
    description: 'Precision milled unibody 6063 aluminum housing with gasket mount dampening, hot-swappable tactile switches, and triple connectivity (2.4G/BT/Type-C).',
    price: 210,
    compareAtPrice: 250,
    currency: 'USD',
    sku: 'TP-KB-75',
    category: 'Electronics',
    subCategory: 'Peripherals',
    tags: ['keyboard', 'mechanical', 'custom', 'cnc-aluminum'],
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 267,
    featured: true,
    status: 'active',
    specifications: {
      'Layout': '75% Compact (82 Keys with Rotary Knob)',
      'Switches': 'Factory Lubed Pre-Travel Tactile 55g',
      'Battery': '4000mAh (Up to 200 hours)',
      'Keycaps': 'Double-shot PBT Cherry Profile',
      'Warranty': '2 Years Limited',
    },
    shipping: {
      freeShipping: true,
      estimatedDays: '1-2 Days',
      cost: 0,
    },
    createdAt: '2026-01-28T16:45:00Z',
  },
  {
    id: 'prod-108',
    vendorId: 'vendor-4',
    vendor: {
      id: 'vendor-4',
      name: 'Titan Pro Ergonomics',
      rating: 4.7,
      reviewCount: 520,
      verified: true,
      location: 'Seattle, WA',
    },
    title: 'TitanLift Heavy Duty Dual-Arm Monitor Gas Spring Mount',
    slug: 'titanlift-dual-arm-monitor-mount',
    description: 'Heavy gauge steel counterbalance spring arms capable of suspending dual 38" ultrawide displays with effortless 360-degree rotation and concealed cable channels.',
    price: 149,
    compareAtPrice: 179,
    currency: 'USD',
    sku: 'TP-MT-02',
    category: 'Home & Workspace',
    subCategory: 'Desk Gear',
    tags: ['monitor-arm', 'ergonomic', 'workspace', 'titanium'],
    stock: 28,
    images: [
      'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.7,
    reviewCount: 112,
    featured: false,
    status: 'active',
    specifications: {
      'Weight Capacity': '33 lbs per arm (Supports up to 38")',
      'VESA Compliance': '75x75mm & 100x100mm quick release',
      'Mounting': 'C-Clamp & Grommet base included',
      'Range': 'Tilt +90/-45, Swivel 180, 360 Rotation',
      'Warranty': '10 Years Structural',
    },
    shipping: {
      freeShipping: true,
      estimatedDays: '2-3 Days',
      cost: 0,
    },
    createdAt: '2026-02-05T14:15:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'MH-ORD-8821',
    customerName: 'Marcus Sterling',
    customerEmail: 'marcus.s@example.com',
    customerPhone: '+1 (555) 349-8812',
    shippingAddress: {
      fullName: 'Marcus Sterling',
      addressLine1: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      postalCode: '97477',
      country: 'United States',
      phone: '+1 (555) 349-8812',
    },
    items: [
      {
        productId: 'prod-101',
        productTitle: 'AuraSphere ANC Spatial Wireless Headphones',
        productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        vendorId: 'vendor-1',
        vendorName: 'Apex Tech Haven',
        price: 289,
        quantity: 1,
      },
      {
        productId: 'prod-103',
        productTitle: 'Nomad Roll-Top Weatherproof Commuter Backpack',
        productImage: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
        vendorId: 'vendor-2',
        vendorName: 'Urban Aura Studio',
        price: 165,
        quantity: 1,
      },
    ],
    subtotal: 454,
    shippingFee: 0,
    tax: 36.32,
    discount: 25,
    total: 465.32,
    paymentMethod: 'credit_card',
    paymentStatus: 'paid',
    status: 'out_for_delivery',
    tracking: {
      orderId: 'MH-ORD-8821',
      carrier: 'FedEx Express Direct',
      trackingNumber: 'FX-889102941-US',
      status: 'out_for_delivery',
      estimatedDelivery: 'Today by 6:00 PM',
      currentLocation: 'Local Courier Hub, Springfield OR',
      checkpoints: [
        {
          id: 'cp-1',
          title: 'Order Placed & Payment Verified',
          location: 'MarketHub Secure Gateway',
          timestamp: 'Sep 25, 09:30 AM',
          completed: true,
          description: 'Payment authorized and escrow hold initiated.',
        },
        {
          id: 'cp-2',
          title: 'Fulfilled by Multiple Vendors',
          location: 'Apex Tech & Urban Aura Studios',
          timestamp: 'Sep 25, 02:15 PM',
          completed: true,
          description: 'Items packed in eco-friendly packaging and sealed.',
        },
        {
          id: 'cp-3',
          title: 'Consolidated & Shipped',
          location: 'FedEx Regional Sort Facility, Portland OR',
          timestamp: 'Sep 26, 08:45 AM',
          completed: true,
          description: 'Package scanned onto overnight linehaul truck.',
        },
        {
          id: 'cp-4',
          title: 'Out for Delivery',
          location: 'Springfield OR Local Dispatch',
          timestamp: 'Today, 08:15 AM',
          completed: true,
          description: 'Driver on route in delivery vehicle #42.',
        },
        {
          id: 'cp-5',
          title: 'Delivered',
          location: 'Customer Front Porch',
          timestamp: 'Estimated: Today, 5:30 PM',
          completed: false,
          description: 'Requires signature upon arrival.',
        },
      ],
    },
    createdAt: '2026-09-25T09:30:00Z',
  },
  {
    id: 'MH-ORD-8794',
    customerName: 'Elena Rostova',
    customerEmail: 'elena.rostova@designcorp.io',
    customerPhone: '+1 (555) 781-9921',
    shippingAddress: {
      fullName: 'Elena Rostova',
      addressLine1: '120 Broadway Suite 400',
      city: 'New York',
      state: 'NY',
      postalCode: '10005',
      country: 'United States',
      phone: '+1 (555) 781-9921',
    },
    items: [
      {
        productId: 'prod-105',
        productTitle: 'Solid American Walnut Modular Desk Shelf',
        productImage: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
        vendorId: 'vendor-3',
        vendorName: 'GreenLeaf Artisans',
        price: 189,
        quantity: 2,
      },
    ],
    subtotal: 378,
    shippingFee: 0,
    tax: 33.55,
    discount: 0,
    total: 411.55,
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    status: 'delivered',
    tracking: {
      orderId: 'MH-ORD-8794',
      carrier: 'UPS Ground NextDay',
      trackingNumber: '1Z9999999999999999',
      status: 'delivered',
      estimatedDelivery: 'Delivered Sep 24',
      currentLocation: 'Front Desk / Reception, NY',
      checkpoints: [
        {
          id: 'cp-201',
          title: 'Order Placed',
          location: 'MarketHub Online',
          timestamp: 'Sep 22, 11:15 AM',
          completed: true,
        },
        {
          id: 'cp-202',
          title: 'Packed by GreenLeaf Artisans',
          location: 'Portland OR',
          timestamp: 'Sep 22, 04:00 PM',
          completed: true,
        },
        {
          id: 'cp-203',
          title: 'In Transit via UPS',
          location: 'New York NY Central Hub',
          timestamp: 'Sep 23, 09:20 PM',
          completed: true,
        },
        {
          id: 'cp-204',
          title: 'Delivered to Receptionist',
          location: 'New York NY',
          timestamp: 'Sep 24, 02:40 PM',
          completed: true,
          description: 'Signed for by R. Chen.',
        },
      ],
    },
    createdAt: '2026-09-22T11:15:00Z',
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    vendorId: 'vendor-1',
    code: 'AUDIO25',
    description: 'Get $25 OFF on premium headphones when spending over $200',
    discountPercent: 15,
    minOrderAmount: 200,
    status: 'active',
    startDate: '2026-09-01',
    endDate: '2026-10-31',
    usageCount: 84,
    maxUses: 200,
  },
  {
    id: 'promo-2',
    vendorId: 'vendor-1',
    code: 'CREATOR4K',
    description: '10% discount on ProVision 4K displays for creative studios',
    discountPercent: 10,
    minOrderAmount: 500,
    status: 'active',
    startDate: '2026-09-15',
    endDate: '2026-11-15',
    usageCount: 31,
    maxUses: 100,
  },
  {
    id: 'promo-3',
    vendorId: 'vendor-2',
    code: 'FALLAURA',
    description: 'Autumn launch: 20% off all weather-resistant technical bags',
    discountPercent: 20,
    minOrderAmount: 120,
    status: 'active',
    startDate: '2026-09-20',
    endDate: '2026-10-20',
    usageCount: 112,
    maxUses: 500,
  },
];

export const VENDOR_STATS_MOCK: Record<string, VendorStats> = {
  'vendor-1': {
    vendorId: 'vendor-1',
    totalRevenue: 64850,
    revenueGrowth: 18.4,
    activeOrders: 42,
    totalProducts: 18,
    lowStockCount: 2,
    averageRating: 4.9,
    totalReviews: 1420,
    fulfillmentRate: 99.4,
    monthlyRevenue: [
      { month: 'Apr', revenue: 7800, orders: 48 },
      { month: 'May', revenue: 9200, orders: 56 },
      { month: 'Jun', revenue: 10400, orders: 63 },
      { month: 'Jul', revenue: 11900, orders: 74 },
      { month: 'Aug', revenue: 12350, orders: 78 },
      { month: 'Sep', revenue: 13200, orders: 82 },
    ],
  },
  'vendor-2': {
    vendorId: 'vendor-2',
    totalRevenue: 38400,
    revenueGrowth: 14.2,
    activeOrders: 27,
    totalProducts: 24,
    lowStockCount: 3,
    averageRating: 4.8,
    totalReviews: 890,
    fulfillmentRate: 98.1,
    monthlyRevenue: [
      { month: 'Apr', revenue: 4900, orders: 38 },
      { month: 'May', revenue: 5400, orders: 42 },
      { month: 'Jun', revenue: 6100, orders: 47 },
      { month: 'Jul', revenue: 7000, orders: 54 },
      { month: 'Aug', revenue: 7300, orders: 57 },
      { month: 'Sep', revenue: 7700, orders: 60 },
    ],
  },
  'vendor-3': {
    vendorId: 'vendor-3',
    totalRevenue: 29800,
    revenueGrowth: 22.8,
    activeOrders: 19,
    totalProducts: 12,
    lowStockCount: 1,
    averageRating: 4.9,
    totalReviews: 610,
    fulfillmentRate: 99.1,
    monthlyRevenue: [
      { month: 'Apr', revenue: 3200, orders: 24 },
      { month: 'May', revenue: 3900, orders: 30 },
      { month: 'Jun', revenue: 4800, orders: 36 },
      { month: 'Jul', revenue: 5500, orders: 41 },
      { month: 'Aug', revenue: 5900, orders: 44 },
      { month: 'Sep', revenue: 6500, orders: 49 },
    ],
  },
  'vendor-4': {
    vendorId: 'vendor-4',
    totalRevenue: 24100,
    revenueGrowth: 9.6,
    activeOrders: 15,
    totalProducts: 14,
    lowStockCount: 2,
    averageRating: 4.7,
    totalReviews: 520,
    fulfillmentRate: 97.8,
    monthlyRevenue: [
      { month: 'Apr', revenue: 3100, orders: 21 },
      { month: 'May', revenue: 3400, orders: 24 },
      { month: 'Jun', revenue: 3900, orders: 28 },
      { month: 'Jul', revenue: 4200, orders: 30 },
      { month: 'Aug', revenue: 4600, orders: 33 },
      { month: 'Sep', revenue: 4900, orders: 35 },
    ],
  },
};
