export const FALLBACK_PRODUCTS = [
  {
    id: 'prod-101',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Apex Tech Haven',
      rating: 4.9,
      verified: true,
      location: 'Austin, TX',
    },
    title: 'AuraSphere ANC Spatial Wireless Headphones',
    slug: 'aurasphere-anc-spatial-headphones',
    description: 'Studio-grade acoustic architecture with active hybrid noise cancellation, 45-hour battery life.',
    price: 289,
    compareAtPrice: 349,
    stock: 24,
    sku: 'APX-AU-01',
    category: 'Electronics',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'],
    specifications: { 'Battery Life': '45 Hours', 'Connectivity': 'Bluetooth 5.4' },
    rating: 4.9,
    reviewCount: 312,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-103',
    vendorId: 'vendor-2',
    vendor: {
      id: 'vendor-2',
      name: 'Urban Aura Studio',
      rating: 4.8,
      verified: true,
      location: 'Brooklyn, NY',
    },
    title: 'Nomad Roll-Top Weatherproof Commuter Backpack',
    slug: 'nomad-rolltop-weatherproof-backpack',
    description: 'Constructed from waterproof 100% recycled Cordura fabric with magnetic Fidlock closures.',
    price: 165,
    compareAtPrice: 195,
    stock: 42,
    sku: 'UA-BK-09',
    category: 'Fashion & Bags',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80'],
    specifications: { 'Capacity': '26 Liters', 'Material': 'Cordura 500D' },
    rating: 4.8,
    reviewCount: 188,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-105',
    vendorId: 'vendor-3',
    vendor: {
      id: 'vendor-3',
      name: 'GreenLeaf Artisans',
      rating: 4.9,
      verified: true,
      location: 'Portland, OR',
    },
    title: 'Solid American Walnut Modular Desk Shelf',
    slug: 'solid-walnut-modular-desk-shelf',
    description: 'Handcrafted from FSC-certified sustainably harvested walnut timber.',
    price: 189,
    compareAtPrice: 220,
    stock: 14,
    sku: 'GL-DS-01',
    category: 'Home & Workspace',
    images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80'],
    specifications: { 'Material': 'American Walnut', 'Capacity': '65 lbs' },
    rating: 4.9,
    reviewCount: 220,
    createdAt: new Date().toISOString(),
  },
];

export const FALLBACK_ORDERS = [
  {
    orderId: 'MH-ORD-8821',
    createdAt: new Date().toISOString(),
    status: 'OUT_FOR_DELIVERY',
    customer: {
      id: 'usr-customer-1',
      fullName: 'Marcus Sterling',
      email: 'marcus.s@example.com',
      phoneNumber: '+1 (555) 349-8812',
    },
    shippingAddress: {
      city: 'Springfield',
      state: 'OR',
      addressLine1: '742 Evergreen Terrace',
    },
    items: [
      {
        productId: 'prod-101',
        productTitle: 'AuraSphere ANC Spatial Wireless Headphones',
        price: 289,
        quantity: 1,
        total: 289,
      },
    ],
    vendorSubtotal: 289,
    tracking: {
      carrier: 'FedEx Express Direct',
      trackingNumber: 'FX-889102941-US',
      status: 'OUT_FOR_DELIVERY',
      estimatedDelivery: new Date().toISOString(),
      currentLocation: 'Local Courier Hub',
      checkpoints: [
        { title: 'Order Placed & Escrow Protected', location: 'MarketHub Gateway', timestamp: 'Today 09:00 AM', completed: true },
        { title: 'Out for Delivery', location: 'Local Hub', timestamp: 'Today 01:15 PM', completed: true },
      ],
    },
  },
];
